[tool.poetry]
name = "wathematica-discord-bot"
version = "0.1.0"
description = ""
authors = ["Takaaki Toda <todatakaaki@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
py-cord = "^2.4.1"
sqlalchemy = "^2.0.23"
aiosqlite = "^0.19.0"
greenlet = "^3.0.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
